import { DocumentType, DocumentCategory } from '@ai-resume/core';

export interface TemplateMetadata {
  id: string;
  name: string;
  documentType: DocumentType;
  category: 'technical' | 'student' | 'executive' | 'academic' | 'creative' | 'general';
  categoryCompatibility: DocumentCategory[];
  intendedUser: string;
  strengths: string[];
  pageSize: 'letter' | 'a4' | 'creative';
  columns: 1 | 2;
  description: string;
  suitableFor: ('student' | 'fresher' | 'technical' | 'non-technical' | 'general')[];
  tags: string[];
  referenceSource: string;
  colorScheme: string;
  fontFamily: 'sans' | 'serif' | 'mono';
  isPopular?: boolean;
  version?: string;
}

/**
 * Complete, Differentiated Template Library (38 Total Templates)
 * - 28 Tailored Resume Templates
 * - 5 Specialized Academic, Clinical, & Technical CV Templates
 * - 5 Structural Cover Letter Templates
 */
export const CANONICAL_TEMPLATES: TemplateMetadata[] = [
  // ==========================================
  // RESUME TEMPLATES (28 Templates)
  // ==========================================
  {
    id: 'template_01',
    name: 'ATS Professional',
    documentType: 'RESUME',
    category: 'technical',
    categoryCompatibility: ['SOFTWARE_IT', 'EXPERIENCED', 'ENTRY_LEVEL', 'BUSINESS_MANAGEMENT', 'CUSTOM'],
    intendedUser: 'Software Engineers, Analysts, and Corporate Professionals',
    strengths: ['Maximized ATS parsing accuracy', 'Conservative clean typography', 'Zero column truncation'],
    pageSize: 'letter',
    columns: 1,
    description: 'Clean single-column standard format with right-aligned contact details and standard section headers designed for ATS readability.',
    suitableFor: ['technical', 'general', 'fresher'],
    tags: ['ATS-Friendly', 'Standard', 'Single Column', 'Tech & Business'],
    referenceSource: 'Standard Industry ATS Template',
    colorScheme: 'Monochrome Slate (#0F172A)',
    fontFamily: 'sans',
    isPopular: true,
    version: '2.0.0'
  },
  {
    id: 'template_02',
    name: 'Classic Corporate',
    documentType: 'RESUME',
    category: 'general',
    categoryCompatibility: ['BUSINESS_MANAGEMENT', 'EXPERIENCED', 'ENTRY_LEVEL', 'CUSTOM'],
    intendedUser: 'Corporate Operations, Account Executives, and Project Coordinators',
    strengths: ['Traditional business hierarchy', 'Prominent role progression', 'Clear section dividers'],
    pageSize: 'letter',
    columns: 1,
    description: 'Traditional corporate layout emphasizing chronological career progression and organizational accomplishments.',
    suitableFor: ['general', 'non-technical'],
    tags: ['Corporate', 'Classic', 'Business', 'Formal'],
    referenceSource: 'Corporate Recruitment Standard',
    colorScheme: 'Navy Slate (#1E293B)',
    fontFamily: 'sans',
    version: '2.0.0'
  },
  {
    id: 'template_03',
    name: 'Compact Tech',
    documentType: 'RESUME',
    category: 'technical',
    categoryCompatibility: ['SOFTWARE_IT', 'ENTRY_LEVEL', 'FRESHER', 'CUSTOM'],
    intendedUser: 'Backend Engineers, Systems Programmers, and Algorithm Specialists',
    strengths: ['High information density', 'Tight vertical margins', 'Direct project bullet points'],
    pageSize: 'letter',
    columns: 1,
    description: 'Ultra-efficient single-page resume format designed to fit extensive technical projects and skills without overflowing.',
    suitableFor: ['technical', 'fresher'],
    tags: ['Compact', 'Technical', '1-Page Fit', 'High Density'],
    referenceSource: 'Tech Industry 1-Page Standard',
    colorScheme: 'Neutral Charcoal (#18181B)',
    fontFamily: 'sans',
    version: '2.0.0'
  },
  {
    id: 'template_04',
    name: 'Experienced / Executive',
    documentType: 'RESUME',
    category: 'executive',
    categoryCompatibility: ['EXPERIENCED', 'BUSINESS_MANAGEMENT', 'CAREER_CHANGE', 'CUSTOM'],
    intendedUser: 'Engineering Managers, Product Leads, and Business Executives',
    strengths: ['Strategic impact highlights', 'Teal executive accents', 'Prominent leadership achievements'],
    pageSize: 'a4',
    columns: 1,
    description: 'High-density leadership format highlighting career progression, team mentorship, strategic initiatives, and quantified business impact.',
    suitableFor: ['non-technical', 'general', 'technical'],
    tags: ['Executive', 'Leadership', 'Management', 'Strategy'],
    referenceSource: 'Executive Leadership Standard',
    colorScheme: 'Teal & Charcoal (#0F766E)',
    fontFamily: 'sans',
    isPopular: true,
    version: '2.0.0'
  },
  {
    id: 'template_05',
    name: 'Minimalist Modern',
    documentType: 'RESUME',
    category: 'general',
    categoryCompatibility: ['ENTRY_LEVEL', 'STUDENT', 'FRESHER', 'CUSTOM'],
    intendedUser: 'General applicants, consultants, and writers',
    strengths: ['Light typography', 'Generous whitespace', 'Clean minimal layout'],
    pageSize: 'letter',
    columns: 1,
    description: 'Minimalist resume layout focusing on typography, whitespace, and straightforward readability.',
    suitableFor: ['general', 'student'],
    tags: ['Minimalist', 'Clean', 'Modern', 'Readable'],
    referenceSource: 'Minimalist Design Standard',
    colorScheme: 'Graphite (#27272A)',
    fontFamily: 'sans',
    version: '2.0.0'
  },
  {
    id: 'template_06',
    name: 'Software Engineer',
    documentType: 'RESUME',
    category: 'technical',
    categoryCompatibility: ['SOFTWARE_IT', 'EXPERIENCED', 'FRESHER', 'CUSTOM'],
    intendedUser: 'Software Engineers, Platform Engineers, and Web Developers',
    strengths: ['Dedicated technology categorization', 'Repository and architecture bullets', 'Clear skill grouping'],
    pageSize: 'letter',
    columns: 1,
    description: 'Structured layout prioritizing engineering stack categorization, core architecture accomplishments, and open source deliverables.',
    suitableFor: ['technical'],
    tags: ['Software', 'Engineering', 'Developer', 'Code'],
    referenceSource: 'Silicon Valley Engineering Standard',
    colorScheme: 'Indigo Slate (#312E81)',
    fontFamily: 'sans',
    isPopular: true,
    version: '2.0.0'
  },
  {
    id: 'template_07',
    name: 'Elegant Serif',
    documentType: 'RESUME',
    category: 'general',
    categoryCompatibility: ['ACADEMIC_RESEARCH', 'CAREER_CHANGE', 'EXPERIENCED', 'CUSTOM'],
    intendedUser: 'Lawyers, Academics, Editors, and Communications Specialists',
    strengths: ['Distinguished editorial typography', 'Formal section dividers', 'Refined presentation'],
    pageSize: 'letter',
    columns: 1,
    description: 'Refined editorial resume format using classic serif headings and balanced typography for traditional industries.',
    suitableFor: ['non-technical', 'general'],
    tags: ['Serif', 'Editorial', 'Formal', 'Classic'],
    referenceSource: 'Editorial & Academic Standard',
    colorScheme: 'Dark Bronze (#1C1917)',
    fontFamily: 'serif',
    version: '2.0.0'
  },
  {
    id: 'template_08',
    name: 'Modern Split Accent',
    documentType: 'RESUME',
    category: 'creative',
    categoryCompatibility: ['SOFTWARE_IT', 'CAREER_CHANGE', 'CUSTOM'],
    intendedUser: 'Product Designers, Frontend Specialists, and Creative Technologists',
    strengths: ['Visual section accents', 'Modern typography badges', 'Distinct hierarchy'],
    pageSize: 'a4',
    columns: 1,
    description: 'Contemporary format with stylized section indicators and accented headers, balancing personality with ATS compliance.',
    suitableFor: ['technical', 'general'],
    tags: ['Design', 'Accent', 'Creative Tech', 'Modern'],
    referenceSource: 'Creative Tech Format',
    colorScheme: 'Emerald & Slate (#047857)',
    fontFamily: 'sans',
    version: '2.0.0'
  },
  {
    id: 'template_09',
    name: 'Data Analyst & Quant',
    documentType: 'RESUME',
    category: 'technical',
    categoryCompatibility: ['SOFTWARE_IT', 'EXPERIENCED', 'BUSINESS_MANAGEMENT', 'CUSTOM'],
    intendedUser: 'Data Scientists, Quantitative Researchers, and BI Analysts',
    strengths: ['Metrics-first bullet formatting', 'Tool stack pills', 'Quantified business impact highlights'],
    pageSize: 'letter',
    columns: 1,
    description: 'Data-driven layout designed to emphasize measurable KPIs, modeling pipelines, statistical methodologies, and tooling mastery.',
    suitableFor: ['technical', 'general'],
    tags: ['Data Science', 'Analytics', 'Metrics', 'Quant'],
    referenceSource: 'Data & Quantitative Standard',
    colorScheme: 'Steel Blue (#1E3A8A)',
    fontFamily: 'sans',
    version: '2.0.0'
  },
  {
    id: 'template_10',
    name: 'Clean Bordered',
    documentType: 'RESUME',
    category: 'general',
    categoryCompatibility: ['ENTRY_LEVEL', 'BUSINESS_MANAGEMENT', 'EXPERIENCED', 'CUSTOM'],
    intendedUser: 'Business Analysts, Account Managers, and Operations Specialists',
    strengths: ['Structured frame borders', 'Clear visual boundaries', 'Balanced spacing'],
    pageSize: 'letter',
    columns: 1,
    description: 'Framed structural layout offering crisp visual demarcation between career milestones and skill proficiencies.',
    suitableFor: ['general', 'non-technical'],
    tags: ['Bordered', 'Framed', 'Organized', 'Business'],
    referenceSource: 'Structured Corporate Format',
    colorScheme: 'Zinc & Coal (#27272A)',
    fontFamily: 'sans',
    version: '2.0.0'
  },
  {
    id: 'template_11',
    name: 'Compact Modern',
    documentType: 'RESUME',
    category: 'technical',
    categoryCompatibility: ['SOFTWARE_IT', 'ENTRY_LEVEL', 'STUDENT', 'CUSTOM'],
    intendedUser: 'Junior Engineers, IT Specialists, and Bootcamp Graduates',
    strengths: ['Tight line heights', 'Compact header', 'Comprehensive skills grid'],
    pageSize: 'letter',
    columns: 1,
    description: 'Streamlined modern layout engineered to pack comprehensive technical experience onto a single cleanly rendered page.',
    suitableFor: ['technical', 'student', 'fresher'],
    tags: ['Compact', 'Junior', 'Bootcamp', 'Modern'],
    referenceSource: 'Bootcamp & Junior Tech Standard',
    colorScheme: 'Slate Navy (#334155)',
    fontFamily: 'sans',
    version: '2.0.0'
  },
  {
    id: 'template_12',
    name: 'Executive Leadership',
    documentType: 'RESUME',
    category: 'executive',
    categoryCompatibility: ['BUSINESS_MANAGEMENT', 'EXPERIENCED', 'CAREER_CHANGE', 'CUSTOM'],
    intendedUser: 'VPs, Directors, General Managers, and Senior Executives',
    strengths: ['Executive summary banner', 'P&L / revenue scale callouts', 'Governance highlights'],
    pageSize: 'letter',
    columns: 1,
    description: 'High-impact executive layout designed to foreground operational leadership, revenue growth, and organizational strategy.',
    suitableFor: ['general', 'non-technical'],
    tags: ['Executive', 'Leadership', 'Director', 'Management'],
    referenceSource: 'Executive Search Standard',
    colorScheme: 'Dark Slate & Gold (#1E293B)',
    fontFamily: 'sans',
    version: '2.0.0'
  },
  {
    id: 'template_13',
    name: 'Engineering Specialist',
    documentType: 'RESUME',
    category: 'technical',
    categoryCompatibility: ['SOFTWARE_IT', 'EXPERIENCED', 'CUSTOM'],
    intendedUser: 'Embedded Engineers, Hardware Specialists, and Systems Architects',
    strengths: ['Technical specification headers', 'Patent and certification slots', 'System-level achievements'],
    pageSize: 'letter',
    columns: 1,
    description: 'Technical resume tailored for deep systems engineering, hardware integration, and core infrastructure roles.',
    suitableFor: ['technical'],
    tags: ['Systems', 'Embedded', 'Hardware', 'Specialist'],
    referenceSource: 'Deep Tech & Engineering Standard',
    colorScheme: 'Charcoal & Amber (#18181B)',
    fontFamily: 'sans',
    version: '2.0.0'
  },
  {
    id: 'template_14',
    name: 'Product Manager',
    documentType: 'RESUME',
    category: 'general',
    categoryCompatibility: ['SOFTWARE_IT', 'BUSINESS_MANAGEMENT', 'EXPERIENCED', 'CUSTOM'],
    intendedUser: 'Technical Product Managers, Group PMs, and Growth Leads',
    strengths: ['Product roadmap metrics', 'User growth callouts', 'Cross-functional leadership focus'],
    pageSize: 'letter',
    columns: 1,
    description: 'Optimized layout for product leaders showcasing user adoption, discovery frameworks, sprint velocity, and business outcomes.',
    suitableFor: ['general', 'technical'],
    tags: ['Product', 'PM', 'Roadmap', 'Growth'],
    referenceSource: 'Tech Product Management Standard',
    colorScheme: 'Deep Navy & Cyan (#0F172A)',
    fontFamily: 'sans',
    version: '2.0.0'
  },
  {
    id: 'template_15',
    name: 'Two-Column Modern',
    documentType: 'RESUME',
    category: 'technical',
    categoryCompatibility: ['SOFTWARE_IT', 'ENTRY_LEVEL', 'CUSTOM'],
    intendedUser: 'Web Developers, UX Designers, and Tech Consultants',
    strengths: ['Left sidebar for skills & credentials', 'Spacious main timeline', 'Contemporary split aesthetic'],
    pageSize: 'letter',
    columns: 2,
    description: 'Two-column modern format balancing a dedicated left sidebar for skills, contact, and education with a wide experience timeline.',
    suitableFor: ['technical', 'general'],
    tags: ['Two Column', 'Sidebar', 'Modern', 'Split'],
    referenceSource: 'Modern Two-Column Design',
    colorScheme: 'Slate & Indigo (#1E293B)',
    fontFamily: 'sans',
    isPopular: true,
    version: '2.0.0'
  },
  {
    id: 'template_17',
    name: 'Modern Professional',
    documentType: 'RESUME',
    category: 'technical',
    categoryCompatibility: ['SOFTWARE_IT', 'CAREER_CHANGE', 'EXPERIENCED', 'CUSTOM'],
    intendedUser: 'Full Stack Developers, Cloud Architects, and Modern Tech Professionals',
    strengths: ['Modern visual hierarchy', 'Subtle blue accents', 'Inline project links and skill pills'],
    pageSize: 'a4',
    columns: 1,
    description: 'Modern professional layout with middle-dot contact separators, subtle blue heading accents, and structured technical sections.',
    suitableFor: ['technical', 'general'],
    tags: ['Modern', 'Blue Accent', 'Full Stack', 'Readable'],
    referenceSource: 'Modern Tech Resume Specification',
    colorScheme: 'Modern Cobalt (#2563EB)',
    fontFamily: 'sans',
    isPopular: true,
    version: '2.0.0'
  },
  {
    id: 'template_18',
    name: 'Full Stack Developer',
    documentType: 'RESUME',
    category: 'technical',
    categoryCompatibility: ['SOFTWARE_IT', 'ENTRY_LEVEL', 'EXPERIENCED', 'CUSTOM'],
    intendedUser: 'Full Stack Engineers, Frontend Specialists, and API Developers',
    strengths: ['Frontend/Backend/DevOps stack segregation', 'Live demo and GitHub links', 'Clean modular spacing'],
    pageSize: 'letter',
    columns: 1,
    description: 'Developer-tailored resume format with dedicated technology categorization and live project showcase fields.',
    suitableFor: ['technical'],
    tags: ['Full Stack', 'Frontend', 'Backend', 'Web Dev'],
    referenceSource: 'Web Engineering Standard',
    colorScheme: 'Dark Slate & Violet (#1E1B4B)',
    fontFamily: 'sans',
    version: '2.0.0'
  },
  {
    id: 'template_19',
    name: 'Minimal Tech',
    documentType: 'RESUME',
    category: 'technical',
    categoryCompatibility: ['SOFTWARE_IT', 'ENTRY_LEVEL', 'FRESHER', 'CUSTOM'],
    intendedUser: 'Software Engineers, DevOps Practitioners, and SREs',
    strengths: ['Monospaced header accents', 'Zero clutter', 'Strict ATS compatibility'],
    pageSize: 'letter',
    columns: 1,
    description: 'Minimalist tech resume combining subtle monospaced metadata with clean sans typography for developer clarity.',
    suitableFor: ['technical', 'fresher'],
    tags: ['Minimal Tech', 'Clean', 'SRE', 'DevOps'],
    referenceSource: 'Modern Minimal Tech Standard',
    colorScheme: 'Charcoal Black (#18181B)',
    fontFamily: 'mono',
    version: '2.0.0'
  },
  {
    id: 'template_20',
    name: 'Cybersecurity & Cloud',
    documentType: 'RESUME',
    category: 'technical',
    categoryCompatibility: ['SOFTWARE_IT', 'EXPERIENCED', 'CUSTOM'],
    intendedUser: 'Security Analysts, Cloud Architects, and DevSecOps Engineers',
    strengths: ['Security clearance and certifications block', 'Incident response achievements', 'Compliance framework tags'],
    pageSize: 'letter',
    columns: 1,
    description: 'Security-focused resume emphasizing certifications (CISSP, CEH, AWS), vulnerability mitigation metrics, and compliance standards.',
    suitableFor: ['technical'],
    tags: ['Cybersecurity', 'Cloud', 'DevSecOps', 'Certifications'],
    referenceSource: 'Information Security Standard',
    colorScheme: 'Slate Crimson (#991B1B)',
    fontFamily: 'sans',
    version: '2.0.0'
  },
  {
    id: 'template_21',
    name: 'Fresher / Student',
    documentType: 'RESUME',
    category: 'student',
    categoryCompatibility: ['STUDENT', 'FRESHER', 'INTERNSHIP', 'ENTRY_LEVEL', 'CUSTOM'],
    intendedUser: 'College Students, Recent Graduates, and Internship Applicants',
    strengths: ['Education and academic coursework prioritized', 'Coding handles callout (GitHub/LeetCode)', 'Project highlights'],
    pageSize: 'letter',
    columns: 1,
    description: 'Student-first resume emphasizing academic degree, GPA/grades, coursework, competitive coding profiles, and capstone projects.',
    suitableFor: ['student', 'fresher', 'technical'],
    tags: ['Student', 'Fresher', 'Internship', 'Campus Placement'],
    referenceSource: 'Campus Placement & University Format',
    colorScheme: 'Classic Dark (#111827)',
    fontFamily: 'sans',
    isPopular: true,
    version: '2.0.0'
  },
  {
    id: 'template_23',
    name: 'Academic-to-Industry',
    documentType: 'RESUME',
    category: 'academic',
    categoryCompatibility: ['ACADEMIC_RESEARCH', 'CAREER_CHANGE', 'EXPERIENCED', 'CUSTOM'],
    intendedUser: 'Postdocs, PhD Researchers, and Academics transitioning to private sector roles',
    strengths: ['Translates scholarly research into commercial value', 'Selected publications & patents', 'Transferable technical leadership'],
    pageSize: 'letter',
    columns: 1,
    description: 'Hybrid resume tailored for PhDs and research scientists moving into corporate R&D, data science, or engineering management.',
    suitableFor: ['technical', 'general'],
    tags: ['Academic', 'PhD', 'Transition', 'Research'],
    referenceSource: 'Academic Transition Standard',
    colorScheme: 'Navy & Slate (#0F172A)',
    fontFamily: 'serif',
    version: '2.0.0'
  },
  {
    id: 'template_24',
    name: 'Finance & Consulting',
    documentType: 'RESUME',
    category: 'executive',
    categoryCompatibility: ['BUSINESS_MANAGEMENT', 'EXPERIENCED', 'CUSTOM'],
    intendedUser: 'Investment Bankers, Management Consultants, and Corporate Strategists',
    strengths: ['Wall Street standard formatting', 'Strict conservative serif layout', 'High density quantified deal experience'],
    pageSize: 'letter',
    columns: 1,
    description: 'Strict investment banking and management consulting standard format optimized for quantitative deals and financial analysis.',
    suitableFor: ['non-technical', 'general'],
    tags: ['Finance', 'Consulting', 'Investment Banking', 'Corporate'],
    referenceSource: 'Wall Street & MBB Consulting Standard',
    colorScheme: 'Monochrome Black (#000000)',
    fontFamily: 'serif',
    version: '2.0.0'
  },
  {
    id: 'template_25',
    name: 'Marketing & Operations',
    documentType: 'RESUME',
    category: 'general',
    categoryCompatibility: ['BUSINESS_MANAGEMENT', 'CAREER_CHANGE', 'ENTRY_LEVEL', 'CUSTOM'],
    intendedUser: 'Digital Marketers, Operations Managers, and Growth Strategists',
    strengths: ['Campaign ROI callouts', 'Tool proficiency matrix', 'Modern clean visual structure'],
    pageSize: 'letter',
    columns: 1,
    description: 'Results-driven resume format focusing on campaign performance metrics, conversion funnels, and operational scale.',
    suitableFor: ['general', 'non-technical'],
    tags: ['Marketing', 'Operations', 'Growth', 'Strategy'],
    referenceSource: 'Marketing & Operations Standard',
    colorScheme: 'Teal Slate (#0D9488)',
    fontFamily: 'sans',
    version: '2.0.0'
  },
  {
    id: 'template_extra_06',
    name: 'Cloud & DevOps Specialist',
    documentType: 'RESUME',
    category: 'technical',
    categoryCompatibility: ['SOFTWARE_IT', 'EXPERIENCED', 'CUSTOM'],
    intendedUser: 'Cloud Engineers, Site Reliability Engineers, and Infrastructure Architects',
    strengths: ['Infrastructure-as-Code callouts', 'Cloud certification badges', 'Uptime & cost-reduction metrics'],
    pageSize: 'letter',
    columns: 1,
    description: 'Infrastructure and DevOps resume tailored to highlight Terraform, Kubernetes, AWS/GCP, and CI/CD automation.',
    suitableFor: ['technical'],
    tags: ['DevOps', 'Cloud', 'Kubernetes', 'AWS'],
    referenceSource: 'Cloud Engineering Standard',
    colorScheme: 'Slate Blue (#1D4ED8)',
    fontFamily: 'sans',
    version: '2.0.0'
  },
  {
    id: 'template_extra_07',
    name: 'UI/UX & Product Design',
    documentType: 'RESUME',
    category: 'creative',
    categoryCompatibility: ['SOFTWARE_IT', 'CUSTOM'],
    intendedUser: 'Product Designers, UX Researchers, and Design System Architects',
    strengths: ['Portfolio URL prominent header', 'Design systems & usability metrics', 'Balanced modern aesthetic'],
    pageSize: 'letter',
    columns: 1,
    description: 'Design-centric resume balancing clean visual hierarchy with ATS-compliant sections for product and UX professionals.',
    suitableFor: ['general', 'technical'],
    tags: ['UI/UX', 'Product Design', 'Figma', 'Creative'],
    referenceSource: 'Product Design Standard',
    colorScheme: 'Indigo Violet (#4338CA)',
    fontFamily: 'sans',
    version: '2.0.0'
  },
  {
    id: 'template_extra_08',
    name: 'Project-Focused Technical',
    documentType: 'RESUME',
    category: 'technical',
    categoryCompatibility: ['SOFTWARE_IT', 'STUDENT', 'FRESHER', 'CUSTOM'],
    intendedUser: 'Self-Taught Developers, Hackathon Winners, and Portfolio Builders',
    strengths: ['Projects section positioned above experience', 'GitHub & live architecture links', 'Technical stack breakdown'],
    pageSize: 'letter',
    columns: 1,
    description: 'Project-first technical resume built for developers whose portfolio of open-source and personal applications is their strongest asset.',
    suitableFor: ['technical', 'student', 'fresher'],
    tags: ['Projects', 'Portfolio', 'Hackathon', 'Open Source'],
    referenceSource: 'Developer Portfolio Standard',
    colorScheme: 'Neutral Slate (#334155)',
    fontFamily: 'sans',
    version: '2.0.0'
  },
  {
    id: 'template_extra_09',
    name: 'International Minimal',
    documentType: 'RESUME',
    category: 'general',
    categoryCompatibility: ['ENTRY_LEVEL', 'EXPERIENCED', 'CAREER_CHANGE', 'CUSTOM'],
    intendedUser: 'Global job applicants, remote workers, and cross-border specialists',
    strengths: ['Language proficiencies block', 'Universal international formatting', 'A4 / Letter auto-balance'],
    pageSize: 'a4',
    columns: 1,
    description: 'Sleek international resume adhering to global recruiting conventions and multi-language support.',
    suitableFor: ['general', 'non-technical'],
    tags: ['International', 'Global', 'Remote', 'Minimal'],
    referenceSource: 'Global Recruiting Format',
    colorScheme: 'Dark Charcoal (#27272A)',
    fontFamily: 'sans',
    version: '2.0.0'
  },
  {
    id: 'template_extra_12',
    name: 'Healthcare & Life Sciences',
    documentType: 'RESUME',
    category: 'general',
    categoryCompatibility: ['ACADEMIC_RESEARCH', 'EXPERIENCED', 'CUSTOM'],
    intendedUser: 'Healthcare Administrators, Clinical Coordinators, and Biotech Specialists',
    strengths: ['Licensing & clinical credentials block', 'Protocol compliance highlights', 'Clean clinical layout'],
    pageSize: 'letter',
    columns: 1,
    description: 'Specialized healthcare and clinical operations resume formatted for hospital systems, biotech firms, and health tech.',
    suitableFor: ['non-technical', 'general'],
    tags: ['Healthcare', 'Biotech', 'Clinical', 'Medical'],
    referenceSource: 'Healthcare & Clinical Standard',
    colorScheme: 'Teal Green (#0F766E)',
    fontFamily: 'sans',
    version: '2.0.0'
  },

  // ==========================================
  // CV TEMPLATES (5 Specialized Templates)
  // ==========================================
  {
    id: 'template_cv_academic',
    name: 'Academic Research CV',
    documentType: 'CV',
    category: 'academic',
    categoryCompatibility: ['ACADEMIC_RESEARCH', 'STUDENT', 'CUSTOM'],
    intendedUser: 'PhD Candidates, Postdocs, Research Scientists, and University Faculty',
    strengths: ['Peer-reviewed publications section', 'Research grants & appointments', 'Academic conference presentations'],
    pageSize: 'a4',
    columns: 1,
    description: 'Comprehensive academic curriculum vitae supporting research appointments, publications, grants, conferences, and scholarly references.',
    suitableFor: ['student', 'fresher', 'technical', 'general'],
    tags: ['Academic CV', 'Research', 'Publications', 'Conferences', 'Serif'],
    referenceSource: 'Standard Academic Curriculum Vitae Format',
    colorScheme: 'Navy & Indigo (#1E1B4B)',
    fontFamily: 'serif',
    isPopular: true,
    version: '2.0.0'
  },
  {
    id: 'template_cv_professional',
    name: 'Professional Executive CV',
    documentType: 'CV',
    category: 'executive',
    categoryCompatibility: ['EXPERIENCED', 'SOFTWARE_IT', 'BUSINESS_MANAGEMENT', 'CUSTOM'],
    intendedUser: 'Senior Consultants, Medical/Legal Specialists, and Principal Engineers',
    strengths: ['Multi-page career history', 'Core competency matrices', 'Project & publication integration'],
    pageSize: 'a4',
    columns: 1,
    description: 'Detailed multi-page professional CV highlighting leadership impact, core competencies, client engagements, and credentials.',
    suitableFor: ['technical', 'non-technical', 'general'],
    tags: ['Professional CV', 'Comprehensive', 'Executive', 'Long Form'],
    referenceSource: 'Executive Leadership CV Format',
    colorScheme: 'Slate Charcoal (#1E293B)',
    fontFamily: 'sans',
    isPopular: true,
    version: '2.0.0'
  },
  {
    id: 'template_cv_medical',
    name: 'Medical & Clinical Specialist CV',
    documentType: 'CV',
    category: 'academic',
    categoryCompatibility: ['ACADEMIC_RESEARCH', 'EXPERIENCED', 'CUSTOM'],
    intendedUser: 'Physicians, Medical Residents, Clinical Researchers, and Healthcare Specialists',
    strengths: ['Clinical rotations & residencies', 'Board certifications & medical licenses', 'Clinical trials & publications'],
    pageSize: 'a4',
    columns: 1,
    description: 'Multi-page clinical CV structured for hospital appointments, medical fellowships, clinical trials, and board certifications.',
    suitableFor: ['general', 'non-technical', 'technical'],
    tags: ['Medical CV', 'Clinical', 'Residency', 'Board Certified'],
    referenceSource: 'Medical Board Curriculum Vitae Format',
    colorScheme: 'Slate Emerald (#065F46)',
    fontFamily: 'sans',
    version: '2.0.0'
  },
  {
    id: 'template_cv_engineering',
    name: 'Technical & Engineering Fellow CV',
    documentType: 'CV',
    category: 'technical',
    categoryCompatibility: ['SOFTWARE_IT', 'EXPERIENCED', 'ACADEMIC_RESEARCH', 'CUSTOM'],
    intendedUser: 'Distinguished Engineers, Principal Architects, and Industrial Researchers',
    strengths: ['Patents & intellectual property registry', 'Technical standards committee leadership', 'Major system architecture milestones'],
    pageSize: 'a4',
    columns: 1,
    description: 'Comprehensive technical curriculum vitae designed for industrial scientists, engineering fellows, and patent holders.',
    suitableFor: ['technical'],
    tags: ['Engineering CV', 'Patents', 'Fellow', 'Architecture'],
    referenceSource: 'IEEE / ACM Technical Fellow CV Format',
    colorScheme: 'Deep Cobalt (#1E3A8A)',
    fontFamily: 'sans',
    version: '2.0.0'
  },
  {
    id: 'template_cv_faculty',
    name: 'Faculty & Postdoctoral Fellowship CV',
    documentType: 'CV',
    category: 'academic',
    categoryCompatibility: ['ACADEMIC_RESEARCH', 'STUDENT', 'CUSTOM'],
    intendedUser: 'Tenure-Track Professors, Department Chairs, and Postdoctoral Scholars',
    strengths: ['Teaching pedagogy & courses taught', 'Sponsored research & federal grants', 'Academic references dossier'],
    pageSize: 'a4',
    columns: 1,
    description: 'Detailed faculty curriculum vitae formatted for tenure reviews, faculty appointments, research grants, and student mentorship records.',
    suitableFor: ['student', 'general', 'technical'],
    tags: ['Faculty CV', 'Teaching', 'Tenure', 'Grants', 'Serif'],
    referenceSource: 'University Faculty Search Dossier Format',
    colorScheme: 'Warm Stone (#292524)',
    fontFamily: 'serif',
    version: '2.0.0'
  },

  // ==========================================
  // COVER LETTER TEMPLATES (5 Templates)
  // ==========================================
  {
    id: 'template_cl_professional',
    name: 'Professional Business Cover Letter',
    documentType: 'COVER_LETTER',
    category: 'executive',
    categoryCompatibility: ['EXPERIENCED', 'BUSINESS_MANAGEMENT', 'CAREER_CHANGE', 'CUSTOM'],
    intendedUser: 'Corporate, finance, and experienced applicants seeking a conventional business letterhead',
    strengths: ['Classic formal letterhead', 'Clear salutation and recipient block', 'Print-optimized serif typography'],
    pageSize: 'letter',
    columns: 1,
    description: 'Conventional formal business cover letter with centered letterhead, formal date/recipient alignment, and sign-off.',
    suitableFor: ['non-technical', 'general', 'fresher'],
    tags: ['Cover Letter', 'Formal', 'Business', 'Serif'],
    referenceSource: 'Executive Formal Letter Format',
    colorScheme: 'Slate Black (#0F172A)',
    fontFamily: 'serif',
    isPopular: true,
    version: '2.0.0'
  },
  {
    id: 'template_cl_modern',
    name: 'Modern Tech Cover Letter',
    documentType: 'COVER_LETTER',
    category: 'technical',
    categoryCompatibility: ['SOFTWARE_IT', 'FRESHER', 'INTERNSHIP', 'ENTRY_LEVEL', 'CUSTOM'],
    intendedUser: 'Software engineers, startup candidates, and tech applicants',
    strengths: ['Contemporary clean sidebar accent', 'Structured value proposition paragraphs', 'ATS keyword alignment'],
    pageSize: 'letter',
    columns: 1,
    description: 'Contemporary tech cover letter featuring clean candidate header, ATS alignment, and structured value-proposition paragraphs.',
    suitableFor: ['student', 'fresher', 'technical', 'general'],
    tags: ['Cover Letter', 'Modern', 'Tech', 'Clean'],
    referenceSource: 'Modern Tech Cover Letter Format',
    colorScheme: 'Royal Blue (#2563EB)',
    fontFamily: 'sans',
    isPopular: true,
    version: '2.0.0'
  },
  {
    id: 'template_cl_minimal',
    name: 'Minimal ATS Cover Letter',
    documentType: 'COVER_LETTER',
    category: 'general',
    categoryCompatibility: ['ENTRY_LEVEL', 'CAREER_CHANGE', 'STUDENT', 'CUSTOM'],
    intendedUser: 'Corporate applicants requiring high-speed ATS parsing and minimal formatting',
    strengths: ['Clean unadorned typography', 'Standardized business spacing', 'Universal ATS readability'],
    pageSize: 'letter',
    columns: 1,
    description: 'Minimalist cover letter stripped of distracting graphics, maximizing scan readability for applicant tracking systems.',
    suitableFor: ['general', 'student', 'fresher'],
    tags: ['Cover Letter', 'Minimal', 'ATS-Friendly', 'Clean'],
    referenceSource: 'Minimal ATS Standard',
    colorScheme: 'Graphite (#27272A)',
    fontFamily: 'sans',
    version: '2.0.0'
  },
  {
    id: 'template_cl_academic',
    name: 'Academic & Research Cover Letter',
    documentType: 'COVER_LETTER',
    category: 'academic',
    categoryCompatibility: ['ACADEMIC_RESEARCH', 'STUDENT', 'CUSTOM'],
    intendedUser: 'Faculty applicants, postdoctoral candidates, and research fellowship seekers',
    strengths: ['Institutional letterhead format', 'Research agenda & teaching statement alignment', 'Formal committee salutations'],
    pageSize: 'letter',
    columns: 1,
    description: 'Scholarly cover letter formatted for university search committees, postdoctoral applications, and research fellowship submissions.',
    suitableFor: ['student', 'general', 'technical'],
    tags: ['Cover Letter', 'Academic', 'Research', 'Faculty', 'Serif'],
    referenceSource: 'Academic Search Committee Standard',
    colorScheme: 'Warm Stone (#292524)',
    fontFamily: 'serif',
    version: '2.0.0'
  },
  {
    id: 'template_cl_creative',
    name: 'Creative & Product Cover Letter',
    documentType: 'COVER_LETTER',
    category: 'creative',
    categoryCompatibility: ['SOFTWARE_IT', 'CUSTOM'],
    intendedUser: 'Product Designers, Creative Directors, and UX Leaders',
    strengths: ['Striking header banner', 'Value proposition callout block', 'Distinctive visual presence'],
    pageSize: 'creative',
    columns: 1,
    description: 'Dynamic cover letter layout with an impactful header block and structured value highlights for creative and product roles.',
    suitableFor: ['general', 'technical'],
    tags: ['Cover Letter', 'Creative', 'Design', 'Product'],
    referenceSource: 'Creative Leadership Format',
    colorScheme: 'Teal & Indigo (#0F766E)',
    fontFamily: 'sans',
    version: '2.0.0'
  }
];

export const TEMPLATE_CATALOG: TemplateMetadata[] = CANONICAL_TEMPLATES;

/**
 * Deterministic helper to get recommended templates for a given DocumentType and Category
 */
export function getRecommendedTemplates(docType: DocumentType, category?: DocumentCategory): TemplateMetadata[] {
  const matchingType = CANONICAL_TEMPLATES.filter(t => t.documentType === docType);
  if (!category) return matchingType;
  const directMatch = matchingType.filter(t => t.categoryCompatibility.includes(category));
  return directMatch.length > 0 ? directMatch : matchingType;
}

export function getTemplateMetaById(id: string): TemplateMetadata | undefined {
  return CANONICAL_TEMPLATES.find(t => t.id === id);
}
