import { DocumentType, DocumentCategory } from '@ai-resume/core';

export interface TemplateMetadata {
  id: string;
  name: string;
  documentType?: DocumentType;
  category: 'technical' | 'student' | 'executive' | 'academic' | 'creative' | 'general';
  categoryCompatibility?: DocumentCategory[];
  pageSize: 'letter' | 'a4';
  columns: 1 | 2;
  description: string;
  suitableFor: ('student' | 'fresher' | 'technical' | 'non-technical' | 'general')[];
  tags: string[];
  referenceSource: string;
  colorScheme: string;
  fontFamily: 'sans' | 'serif' | 'mono';
  isPopular?: boolean;
  version?: string;
}

const RAW_TEMPLATE_CATALOG: TemplateMetadata[] = [
  {
    id: 'template_01',
    name: 'Minimal Tech Clean',
    category: 'technical',
    pageSize: 'letter',
    columns: 1,
    description: 'Clean single-column developer format with right-aligned contact details and portfolio callout.',
    suitableFor: ['student', 'fresher', 'technical'],
    tags: ['Minimalist', 'Tech', 'Clean', 'Letter'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 1)',
    colorScheme: 'Monochrome Slate (#0F172A)',
    fontFamily: 'sans',
    isPopular: true
  },
  {
    id: 'template_02',
    name: 'Classic Academic Blue',
    category: 'academic',
    pageSize: 'a4',
    columns: 1,
    description: 'Traditional academic style with deep navy heading accents, bottom borders, and serif typography.',
    suitableFor: ['student', 'fresher', 'technical', 'general'],
    tags: ['Academic', 'Navy Blue', 'Serif', 'A4'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 2)',
    colorScheme: 'Deep Navy (#1E3A8A)',
    fontFamily: 'serif',
    isPopular: true
  },
  {
    id: 'template_03',
    name: 'Enterprise Java Professional',
    category: 'technical',
    pageSize: 'a4',
    columns: 1,
    description: 'Structured enterprise engineer layout with categorized competencies grid and clean date alignment.',
    suitableFor: ['technical', 'general', 'fresher'],
    tags: ['Enterprise', 'Backend', 'Java', 'A4'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 3)',
    colorScheme: 'Charcoal (#1E293B)',
    fontFamily: 'sans'
  },
  {
    id: 'template_04',
    name: 'People Operations Executive',
    category: 'executive',
    pageSize: 'a4',
    columns: 1,
    description: 'Executive leadership layout with warm teal accents and strong highlight metrics.',
    suitableFor: ['non-technical', 'general'],
    tags: ['Executive', 'HR', 'Teal', 'A4'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 4)',
    colorScheme: 'Teal & Charcoal (#0F766E)',
    fontFamily: 'sans'
  },
  {
    id: 'template_05',
    name: 'Strategy & Operations Compact',
    category: 'general',
    pageSize: 'a4',
    columns: 1,
    description: 'High-density corporate format with capitalized bold headers and full-width underline rules.',
    suitableFor: ['non-technical', 'general', 'fresher'],
    tags: ['High Density', 'Corporate', 'Underline', 'A4'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 5)',
    colorScheme: 'Pure Black (#000000)',
    fontFamily: 'sans',
    isPopular: true
  },
  {
    id: 'template_06',
    name: 'Harshibar Modern Developer',
    category: 'technical',
    pageSize: 'letter',
    columns: 1,
    description: 'Modern developer layout with icon badges in contact bar, italicized roles, and compact project tech pills.',
    suitableFor: ['student', 'fresher', 'technical'],
    tags: ['Developer', 'Icons', 'Popular', 'Letter'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 6)',
    colorScheme: 'Slate Gray (#334155)',
    fontFamily: 'sans',
    isPopular: true
  },
  {
    id: 'template_07',
    name: 'Supply Chain & Ops Specialist',
    category: 'general',
    pageSize: 'a4',
    columns: 1,
    description: 'Operational resume with 3-column expertise tag cloud and highlighted KPI bullet metrics.',
    suitableFor: ['non-technical', 'general'],
    tags: ['Operations', 'Supply Chain', 'Grid', 'A4'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 7)',
    colorScheme: 'Steel Blue (#1E40AF)',
    fontFamily: 'sans'
  },
  {
    id: 'template_08',
    name: 'Engineering Manager Diamond',
    category: 'technical',
    pageSize: 'a4',
    columns: 1,
    description: 'Single-column leadership layout with diamond separators and dual technical/management skills block.',
    suitableFor: ['technical', 'general'],
    tags: ['Engineering Manager', 'Diamond', 'Leadership', 'A4'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 8)',
    colorScheme: 'Dark Charcoal (#1F2937)',
    fontFamily: 'sans'
  },
  {
    id: 'template_09',
    name: 'Bangalore SDE Tier-1',
    category: 'technical',
    pageSize: 'a4',
    columns: 1,
    description: 'Top-tier tech fresher format highlighting competitive coding handles, tech stack bullets, and achievements.',
    suitableFor: ['student', 'fresher', 'technical'],
    tags: ['SDE', 'Competitive Coding', 'Tier-1', 'A4'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 9)',
    colorScheme: 'Indigo (#3730A3)',
    fontFamily: 'sans',
    isPopular: true
  },
  {
    id: 'template_10',
    name: 'Career Returner / Hybrid Clean',
    category: 'general',
    pageSize: 'letter',
    columns: 1,
    description: 'Format highlighting recent certifications and upskilling alongside historical experience.',
    suitableFor: ['fresher', 'technical', 'general'],
    tags: ['Career Transition', 'Certifications', 'Clean', 'Letter'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 10)',
    colorScheme: 'Dark Slate (#1E293B)',
    fontFamily: 'sans'
  },
  {
    id: 'template_11',
    name: 'Fintech / Quantitative Analyst',
    category: 'academic',
    pageSize: 'a4',
    columns: 1,
    description: 'Structured layout emphasizing quantitative metrics, financial tools, and top-ranked education.',
    suitableFor: ['student', 'fresher', 'technical', 'non-technical'],
    tags: ['Fintech', 'Quant', 'Finance', 'A4'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 11)',
    colorScheme: 'Navy & Gold Accent (#172554)',
    fontFamily: 'serif'
  },
  {
    id: 'template_12',
    name: 'Chartered Accountant / Finance',
    category: 'general',
    pageSize: 'a4',
    columns: 1,
    description: 'Formal accounting and auditing layout with CA credentials, articleship training, and tax compliance sections.',
    suitableFor: ['non-technical', 'general', 'fresher'],
    tags: ['CA', 'Finance', 'Articleship', 'A4'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 12)',
    colorScheme: 'Classic Black (#000000)',
    fontFamily: 'serif'
  },
  {
    id: 'template_13',
    name: 'Management Consultant Elite',
    category: 'executive',
    pageSize: 'a4',
    columns: 1,
    description: 'Tier-1 strategy consulting format (McKinsey / BCG style) with client engagement impact and education top.',
    suitableFor: ['student', 'fresher', 'non-technical', 'general'],
    tags: ['Consulting', 'Elite', 'Strategy', 'A4'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 13)',
    colorScheme: 'Charcoal Black (#111827)',
    fontFamily: 'serif',
    isPopular: true
  },
  {
    id: 'template_14',
    name: 'MBA Strategic Leader',
    category: 'student',
    pageSize: 'letter',
    columns: 1,
    description: 'Standardized business school format with dual degree blocks, academic projects, and committee leadership.',
    suitableFor: ['student', 'fresher', 'non-technical', 'general'],
    tags: ['MBA', 'B-School', 'Leadership', 'Letter'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 14)',
    colorScheme: 'Dark Slate (#0F172A)',
    fontFamily: 'sans'
  },
  {
    id: 'template_15',
    name: 'Deedy LaTeX Academic / SDE',
    category: 'technical',
    pageSize: 'letter',
    columns: 2,
    description: 'Iconic two-column asymmetric layout (sidebar + main) inspired by the famous Deedy Resume LaTeX template.',
    suitableFor: ['student', 'fresher', 'technical'],
    tags: ['Deedy', 'Two Column', 'LaTeX', 'Letter'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 15)',
    colorScheme: 'Deep Blue (#2563EB)',
    fontFamily: 'sans',
    isPopular: true
  },
  {
    id: 'template_17',
    name: 'Full Stack Dev Modern Blue',
    category: 'technical',
    pageSize: 'a4',
    columns: 1,
    description: 'Modern engineering resume with middle dot contact separators and inline GitHub repository links.',
    suitableFor: ['student', 'fresher', 'technical'],
    tags: ['Full Stack', 'Modern Blue', 'Web', 'A4'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 17)',
    colorScheme: 'Royal Blue (#2563EB)',
    fontFamily: 'sans'
  },
  {
    id: 'template_18',
    name: 'Cloud DevOps & SRE Pro',
    category: 'technical',
    pageSize: 'a4',
    columns: 1,
    description: 'Cloud infrastructure resume with cloud certification badges and categorized CI/CD toolchains.',
    suitableFor: ['technical', 'general'],
    tags: ['DevOps', 'Cloud', 'SRE', 'A4'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 18)',
    colorScheme: 'Steel Slate (#334155)',
    fontFamily: 'sans'
  },
  {
    id: 'template_19',
    name: 'Embedded Systems & Hardware',
    category: 'technical',
    pageSize: 'letter',
    columns: 1,
    description: 'Firmware and embedded engineer format with micro-controller matrices and patent/publication sections.',
    suitableFor: ['technical', 'student', 'fresher'],
    tags: ['Embedded', 'Hardware', 'Firmware', 'Letter'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 19)',
    colorScheme: 'Charcoal (#1E293B)',
    fontFamily: 'sans'
  },
  {
    id: 'template_20',
    name: 'IIT / IIIT Placement Format',
    category: 'student',
    pageSize: 'a4',
    columns: 1,
    description: 'Standard Indian Premier Engineering Institute (IIT/NIT/IIIT) placement cell format with 4-column academic table.',
    suitableFor: ['student', 'fresher', 'technical'],
    tags: ['IIT Placement', 'College Table', 'Campus', 'A4'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 20)',
    colorScheme: 'LaTeX Black (#000000)',
    fontFamily: 'serif',
    isPopular: true
  },
  {
    id: 'template_21',
    name: 'Engineering Fresher Modular',
    category: 'student',
    pageSize: 'letter',
    columns: 1,
    description: 'Student resume with competitive coding ribbon (LeetCode, HackerRank, GitHub) and coursework split tags.',
    suitableFor: ['student', 'fresher', 'technical'],
    tags: ['Fresher', 'Coding Handles', 'Modular', 'Letter'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 21)',
    colorScheme: 'Neutral Black (#111827)',
    fontFamily: 'sans'
  },
  {
    id: 'template_23',
    name: 'Content Strategist & Writer',
    category: 'creative',
    pageSize: 'a4',
    columns: 1,
    description: 'Creative professional format with prominent portfolio showcase link, SEO metrics, and editorial typography.',
    suitableFor: ['non-technical', 'general', 'fresher'],
    tags: ['Content', 'Writer', 'Portfolio', 'A4'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 23)',
    colorScheme: 'Plum & Slate (#4C1D95)',
    fontFamily: 'serif'
  },
  {
    id: 'template_24',
    name: 'GitHub Actions CV / Open Source',
    category: 'technical',
    pageSize: 'a4',
    columns: 1,
    description: 'Open source developer resume with CI/CD automated notice, DOI publication links, and structured web badges.',
    suitableFor: ['student', 'fresher', 'technical'],
    tags: ['Open Source', 'GitHub CV', 'CI/CD', 'A4'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 24)',
    colorScheme: 'Charcoal Black (#1F2937)',
    fontFamily: 'mono'
  },
  {
    id: 'template_25',
    name: 'Minimalist Classic Tech',
    category: 'student',
    pageSize: 'letter',
    columns: 1,
    description: 'Projects-first traditional resume with diamond dividers, ideal for fresh graduates and internship applicants.',
    suitableFor: ['student', 'fresher', 'technical'],
    tags: ['Projects First', 'Fresher', 'Minimalist', 'Letter'],
    referenceSource: 'ATS Friendly Resume Pack(25).pdf (Page 25)',
    colorScheme: 'Pure Black (#000000)',
    fontFamily: 'sans',
    isPopular: true
  },
  {
    id: 'template_extra_06',
    name: 'Staff SWE Infrastructure',
    category: 'technical',
    pageSize: 'letter',
    columns: 1,
    description: 'High-performance systems engineer resume with team callout, latency/throughput metrics, and distributed systems focus.',
    suitableFor: ['technical', 'student', 'fresher'],
    tags: ['Staff SWE', 'Infrastructure', 'Scale', 'Letter'],
    referenceSource: 'ATS resume 6.pdf',
    colorScheme: 'Monochrome Slate (#0F172A)',
    fontFamily: 'sans'
  },
  {
    id: 'template_extra_07',
    name: 'Mobile iOS / Client Engineer',
    category: 'technical',
    pageSize: 'letter',
    columns: 1,
    description: 'Client engineer resume highlighting published App Store applications, user retention, and client performance.',
    suitableFor: ['technical', 'student', 'fresher'],
    tags: ['Mobile', 'iOS', 'Published Apps', 'Letter'],
    referenceSource: 'ATS resume 7.pdf',
    colorScheme: 'Charcoal Black (#18181B)',
    fontFamily: 'sans'
  },
  {
    id: 'template_extra_08',
    name: 'Product Manager / Growth Lead',
    category: 'executive',
    pageSize: 'letter',
    columns: 1,
    description: 'Product leadership resume with feature launch impact, A/B test outcome metrics, and product pod branding.',
    suitableFor: ['non-technical', 'technical', 'general'],
    tags: ['Product Manager', 'Growth', 'A/B Testing', 'Letter'],
    referenceSource: 'ATS resume 8.pdf',
    colorScheme: 'Dark Charcoal (#111827)',
    fontFamily: 'sans',
    isPopular: true
  },
  {
    id: 'template_extra_09',
    name: 'SDET / QA Automation Architect',
    category: 'technical',
    pageSize: 'a4',
    columns: 1,
    description: 'QA and automation resume featuring a comprehensive testing frameworks matrix right below the summary.',
    suitableFor: ['technical', 'student', 'fresher'],
    tags: ['SDET', 'QA Automation', 'Testing', 'A4'],
    referenceSource: 'ATS resume 9.pdf',
    colorScheme: 'Deep Slate (#1E293B)',
    fontFamily: 'sans'
  },
  {
    id: 'template_extra_12',
    name: 'Technical Writer & Docs Engineer',
    category: 'creative',
    pageSize: 'a4',
    columns: 1,
    description: 'Developer documentation resume featuring docs-as-code toolchains, API reference links, and published articles.',
    suitableFor: ['non-technical', 'technical', 'student', 'fresher', 'general'],
    tags: ['Technical Writer', 'Documentation', 'API Docs', 'A4'],
    referenceSource: 'ATS resume 12.pdf',
    colorScheme: 'Charcoal Black (#1F2937)',
    fontFamily: 'sans'
  },
  {
    id: 'template_cv_academic',
    name: 'Academic & Scholar CV',
    documentType: 'CV',
    category: 'academic',
    categoryCompatibility: ['ACADEMIC_RESEARCH', 'STUDENT', 'CUSTOM'],
    pageSize: 'a4',
    columns: 1,
    description: 'Comprehensive academic curriculum vitae with research appointments, peer-reviewed publications, grants, and scholarly references.',
    suitableFor: ['student', 'fresher', 'technical', 'general'],
    tags: ['Academic CV', 'Research', 'Publications', 'Conferences', 'A4'],
    referenceSource: 'Standard Academic Curriculum Vitae Format',
    colorScheme: 'Navy & Gold Accent (#1E1B4B)',
    fontFamily: 'serif',
    isPopular: true,
    version: '1.0.0'
  },
  {
    id: 'template_cv_professional',
    name: 'Executive Career CV',
    documentType: 'CV',
    category: 'executive',
    categoryCompatibility: ['EXPERIENCED', 'SOFTWARE_IT', 'BUSINESS_MANAGEMENT', 'CUSTOM'],
    pageSize: 'a4',
    columns: 1,
    description: 'Detailed multi-page professional CV highlighting leadership impact, core competencies, client projects, and credentials.',
    suitableFor: ['technical', 'non-technical', 'general'],
    tags: ['Professional CV', 'Executive', 'Comprehensive', 'A4'],
    referenceSource: 'Executive Leadership CV Format',
    colorScheme: 'Slate Charcoal (#1E293B)',
    fontFamily: 'sans',
    isPopular: true,
    version: '1.0.0'
  },
  {
    id: 'template_cl_modern',
    name: 'Modern ATS Cover Letter',
    documentType: 'COVER_LETTER',
    category: 'technical',
    categoryCompatibility: ['SOFTWARE_IT', 'FRESHER', 'INTERNSHIP', 'ENTRY_LEVEL', 'CUSTOM'],
    pageSize: 'letter',
    columns: 1,
    description: 'Contemporary tech cover letter featuring left-accented candidate credentials, ATS keyword alignment, and structured paragraphs.',
    suitableFor: ['student', 'fresher', 'technical', 'general'],
    tags: ['Cover Letter', 'Modern', 'ATS Friendly', 'Letter'],
    referenceSource: 'Modern Tech Cover Letter Format',
    colorScheme: 'Royal Blue (#2563EB)',
    fontFamily: 'sans',
    isPopular: true,
    version: '1.0.0'
  },
  {
    id: 'template_cl_professional',
    name: 'Executive Formal Cover Letter',
    documentType: 'COVER_LETTER',
    category: 'executive',
    categoryCompatibility: ['EXPERIENCED', 'BUSINESS_MANAGEMENT', 'CAREER_CHANGE', 'CUSTOM'],
    pageSize: 'letter',
    columns: 1,
    description: 'Classic executive cover letter with traditional centered letterhead, formal salutation, recipient block, and signature.',
    suitableFor: ['non-technical', 'general', 'fresher'],
    tags: ['Cover Letter', 'Executive', 'Formal', 'Serif', 'Letter'],
    referenceSource: 'Executive Formal Letter Format',
    colorScheme: 'Slate Black (#0F172A)',
    fontFamily: 'serif',
    isPopular: true,
    version: '1.0.0'
  }
];

export const TEMPLATE_CATALOG: TemplateMetadata[] = RAW_TEMPLATE_CATALOG.map(t => ({
  ...t,
  documentType: t.documentType || 'RESUME'
}));
